### ISSUE TITLE
help with ir controller 

### ISSUE THREAD

**Issue by unixtall** [elad-bar/ha-tuya-dynamic#12]
I have a IR controller with temperature and humidity. I see in the json the following data, but i dont know how to use.

 "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "34",
    "app_type": "smartlife",
    "mqtt_connected": false,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "IR Dormitorio",
    "model": "S06ProWB3S\u65b0\u754c\u9762",
    "category": "wnykq",
    "product_id": "whs3cty93fzrqkpt",
    "product_name": "Smart IR",
    "online": true,
    "sub": false,
    "time_zone": "+01:00",
    "active_time": "2023-01-24T14:48:35+00:00",
    "create_time": "2023-01-24T14:48:35+00:00",
    "update_time": "2023-01-24T14:48:52+00:00",
    "function": {},
    "status_range": {
      "va_temperature": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": -200,
          "max": 800,
          "scale": 1,
          "step": 1
        }
      },
      "va_humidity": {
        "type": "Integer",
        "value": {
          "unit": "%",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      }
    },
    "status": {
      "va_temperature": 160,
      "va_humidity": 61,
      "temp_current": 133,
      "humidity_value": 67
    },
    "home_assistant": {
      "name": "IR Dormitorio",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }
  }

Can someone help me?

**Comment by elad-bar** [comment]
Seems that device is weather station not in AC remote,
Did you follow the instructions from the read me how to make Tuya to expose all DP codes?

Thanks

**Comment by unixtall** [comment]
Yes you can see in the screenshots

![2023-01-25 20_45_11-Tuya IoT Platform](https://user-images.githubusercontent.com/26282494/214672613-f7b76452-1b35-4fb4-be9b-fbc01e26f3d6.png)
![2023-01-25 20_45_40-Tuya IoT Platform](https://user-images.githubusercontent.com/26282494/214672621-41b59c32-c72c-4ea6-9e68-422d4239daea.png)
![2023-01-25 20_44_48-Tuya IoT Platform](https://user-images.githubusercontent.com/26282494/214672626-4f66ecd8-1fcb-4205-b4b9-46c903be9a63.png)

**Comment by elad-bar** [comment]
Can you please share a screenshot from the tuya app?

Thanks

**Comment by unixtall** [comment]
There you are

**Comment by elad-bar** [comment]
@unixtall no screenshot is attached, can you please try again

thanks

**Comment by unixtall** [comment]
Sorry.

![Screenshot_20230126_062516_Smart Life](https://user-images.githubusercontent.com/26282494/214783900-3a3b973f-fdd5-4882-82a4-cd350d899e31.jpg)
![Screenshot_20230126_062457_Smart Life](https://user-images.githubusercontent.com/26282494/214783917-54033eee-a724-4669-a641-f5b7dfbd6c3e.jpg)

**Comment by elad-bar** [comment]
it seems that only sensors are available also in the mobile app, how do you control the ac?

thanks

**Comment by unixtall** [comment]
You have to add the device and learn the code. I have nothing because the sensor it is New. I would like to use this with node red for automation.  For example when temp is less than 16 degreess, ac Will activate. But the problem it the original tuya integration says that this device is unsupported.  I Will show show how i can learn the ir code for a device
![Screenshot_20230126_062457_Smart Life](https://user-images.githubusercontent.com/26282494/214792990-06f8a5c1-dd58-491e-87c0-4e51c0707f10.jpg)
![Screenshot_20230126_093957_Smart Life](https://user-images.githubusercontent.com/26282494/214793016-078c3140-e579-4375-a9b6-ebe764ff2cf3.jpg)
![Screenshot_20230126_094005_Smart Life](https://user-images.githubusercontent.com/26282494/214793044-2009b703-8a12-4ee5-aba9-2ed1528b7b16.jpg)

**Comment by elad-bar** [comment]
Project is no longer supported, switched to LocalTuya + Zigbee2MQTT
