### ISSUE TITLE
New Device Alarm Siren

### ISSUE THREAD

**Issue by josepira58** [elad-bar/ha-tuya-dynamic#14]
Hello, first of all congratulations for the work and the HA project, it's great. I would like to be able to use this device in HA, it is a siren or alarm, which has a temperature and humidity sensor... I did the steps to add the devices from tuyaIoT, and the values appear in the json, but I cannot download it from the CE integration of yours, an error appears on the server when downloading the diagnosis. I leave the diagnosis of the alarm, of your integration.
Thanks in advance!

"data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "34",
    "app_type": "smartlife",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "Alarma",
    "model": "NAS-AB02W0-1",
    "category": "sgbj",
    "product_id": "eISESdwVoVIV3axj",
    "product_name": "Siren",
    "online": true,
    "sub": false,
    "time_zone": "+01:00",
    "active_time": "2019-12-31T18:15:03+00:00",
    "create_time": "2019-12-11T14:44:08+00:00",
    "update_time": "2023-02-17T07:29:09+00:00",
    "function": {
      "Alarmtype": {
        "type": "Enum",
        "value": {
          "range": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18"
          ]
        }
      },
      "AlarmPeriod": {
        "type": "Integer",
        "value": {
          "unit": "\u79d2",
          "min": 0,
          "max": 1800,
          "scale": 0,
          "step": 10
        }
      },
      "AlarmSwitch": {
        "type": "Boolean",
        "value": {}
      },
      "temperature_min_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": -20,
          "max": 80,
          "scale": 0,
          "step": 1
        }
      },
      "temperature_max_set": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": -20,
          "max": 80,
          "scale": 0,
          "step": 1
        }
      },
      "humidity_min_set": {
        "type": "Integer",
        "value": {
          "unit": "%RH",
          "min": 1,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      "humidity_max_set": {
        "type": "Integer",
        "value": {
          "unit": "%RH",
          "min": 1,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      "C_F": {
        "type": "Boolean",
        "value": {}
      },
      "temperatureswitch": {
        "type": "Boolean",
        "value": {}
      },
      "humidityswitch": {
        "type": "Boolean",
        "value": {}
      }
    },
    "status_range": {
      "BatteryStatus": {
        "type": "Enum",
        "value": {
          "range": [
            "0",
            "1",
            "2",
            "3",
            "4"
          ]
        }
      },
      "Alarmtype": {
        "type": "Enum",
        "value": {
          "range": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18"
          ]
        }
      },
      "AlarmPeriod": {
        "type": "Integer",
        "value": {
          "unit": "\u79d2",
          "min": 0,
          "max": 1800,
          "scale": 0,
          "step": 10
        }
      },
      "AlarmSwitch": {
        "type": "Boolean",
        "value": {}
      },
      "temperature": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": -20,
          "max": 80,
          "scale": 0,
          "step": 1
        }
      },
      "humidity": {
        "type": "Integer",
        "value": {
          "unit": "%RH",
          "min": 1,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      "temperature_min_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": -20,
          "max": 80,
          "scale": 0,
          "step": 1
        }
      },
      "temperature_max_set": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": -20,
          "max": 80,
          "scale": 0,
          "step": 1
        }
      },
      "humidity_min_set": {
        "type": "Integer",
        "value": {
          "unit": "%RH",
          "min": 1,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      "humidity_max_set": {
        "type": "Integer",
        "value": {
          "unit": "%RH",
          "min": 1,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      "C_F": {
        "type": "Boolean",
        "value": {}
      },
      "temperatureswitch": {
        "type": "Boolean",
        "value": {}
      },
      "humidityswitch": {
        "type": "Boolean",
        "value": {}
      },
      "Alarm_Status": {
        "type": "Enum",
        "value": {
          "range": [
            "0",
            "1",
            "2",
            "3",
            "4",
            "6",
            "8",
            "9",
            "12"
          ]
        }
      }
    },
    "status": {
      "BatteryStatus": 4,
      "Alarmtype": 12,
      "AlarmPeriod": 60,
      "AlarmSwitch": false,
      "temperature": 16,
      "humidity": 48,
      "temperature_min_set": -5,
      "temperature_max_set": 40,
      "humidity_min_set": 45,
      "humidity_max_set": 80,
      "C_F": true,
      "temperatureswitch": true,
      "humidityswitch": false,
      "Alarm_Status": 0
    },
    "home_assistant": {
      "name": "Alarma",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }
  }

The values are in the status tag of the JSON!!

**Comment by elad-bar** [comment]
Project is no longer supported, switched to LocalTuya + Zigbee2MQTT
