### ISSUE TITLE
New device Pir sensor

### ISSUE THREAD

**Issue by josepira58** [elad-bar/ha-tuya-dynamic#15]
Hi, I have a motion sensor not supported by HA, I'll leave it here. greetings!

  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "34",
    "app_type": "smartlife",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "PIR Sensor",
    "model": "DP-WP001",
    "category": "pir",
    "product_id": "XFD2nSDKxFlGV5sV",
    "product_name": "PIR Sensor",
    "online": true,
    "sub": false,
    "time_zone": "+01:00",
    "active_time": "2021-04-22T20:30:14+00:00",
    "create_time": "2019-12-11T14:50:16+00:00",
    "update_time": "2021-12-21T01:02:50+00:00",
    "function": {},
    "status_range": {
      "PIR": {
        "type": "Enum",
        "value": {
          "range": [
            "pir"
          ]
        }
      },
      "battery": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": 0,
          "max": 10000,
          "scale": 0,
          "step": 1
        }
      }
    },
    "status": {
      "PIR": "pir",
      "battery": 100
    },
    "home_assistant": {
      "name": "PIR Sensor",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "motion",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.pir_sensor",
            "state": "unavailable",
            "attributes": {
              "restored": true,
              "device_class": "motion",
              "supported_features": 0
            },
            "last_changed": "2023-02-17T12:34:35.045157+00:00",
            "last_updated": "2023-02-17T12:34:35.045157+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "",
          "state": {
            "entity_id": "sensor.pir_sensor_battery",
            "state": "unavailable",
            "attributes": {
              "restored": true,
              "state_class": "measurement",
              "friendly_name": "Battery",
              "supported_features": 0,
              "unit_of_measurement": ""
            },
            "last_changed": "2023-02-17T12:34:35.045657+00:00",
            "last_updated": "2023-02-17T12:34:35.045657+00:00"
          }
        }
      ]
    }
  }

**Comment by elad-bar** [comment]
Project is no longer supported, switched to LocalTuya + Zigbee2MQTT
