### ISSUE TITLE
New IR Device Domo-22pro

### ISSUE THREAD

**Issue by migueljal** [elad-bar/ha-tuya-dynamic#16]
I followed the instructions to add new devices as seem that they are not supported. See below some data:

Json:
 {
        "name": "Domo-22pro",
        "model": "IR Remote Control with T&H",
        "category": "wnykq",
        "product_id": "siipb1q7swavknbg",
        "product_name": "Smart IR",
        "online": true,
        "sub": false,
        "time_zone": "-03:00",
        "active_time": "2023-01-23T15:59:59+00:00",
        "create_time": "2023-01-23T15:59:59+00:00",
        "update_time": "2023-01-25T21:50:35+00:00",
        "function": {},
        "status_range": {},
        "status": {},
        "home_assistant": {
          "name": "Consultorio Julieta",
          "name_by_user": null,
          "disabled": false,
          "disabled_by": null,
          "entities": []
        }

![domo22](https://user-images.githubusercontent.com/36607785/219904816-3376b6b2-c6bd-44b7-91b1-128fe03cd93b.png)

**Comment by elad-bar** [comment]
Project is no longer supported, switched to LocalTuya + Zigbee2MQTT
