### ISSUE TITLE
Unsupported Device - Smart IR S18

### ISSUE THREAD

**Issue by RPSouto** [elad-bar/ha-tuya-dynamic#17]
name": "IR (Escrit\u00f3rio)", 
"model": "", 
"category": "wnykq", 
"product_id": "pwdxov5sa0tc4jky",
 "product_name": "Smart IR",
 "online": false,
 "sub": false, 
"time_zone": "+01:00",
 "active_time": "2023-04-11T11:04:18+00:00",
 "create_time": "2023-04-11T11:04:18+00:00",
 "update_time": "2023-04-11T11:04:49+00:00",
 "function": {}, 
"status_range": {},
 "status": {}, 
"home_assistant": { "name": "IR (Escrit\u00f3rio)", "name_by_user": null, "disabled": false, "disabled_by": null, "entities": []

![IMG_20230412_070442.jpg](https://user-images.githubusercontent.com/50775080/231365726-5e4b5a45-69b3-43fb-a6d6-84d91a3f4088.jpg)

**Comment by elad-bar** [comment]
Project is no longer supported, switched to LocalTuya + Zigbee2MQTT
