### ISSUE TITLE
Error to add a repository

### ISSUE THREAD

**Issue by Bobsilvio** [elad-bar/ha-tuya-dynamic#5]
hi, solution for this? --> "hacs repository structure for master is not compliant"

**Comment by elad-bar** [comment]
Will check it later today

**Comment by scriptpigeon** [comment]
+1 for Tuya CE. Unable to search for it in HACS and ability to add my Proscenic T22 Air Fryer to HA via automated DP config change. So frustrating to see items in diagnostics, but Tuya not supporting.

**Comment by Mocheto** [comment]
same here

**Comment by elad-bar** [comment]
missed one folder 😱, now it should work, 
please let me know if it works for you, thanks

**Comment by elad-bar** [comment]
can we close this issue?

thanks

**Comment by Bobsilvio** [comment]
yes
