### ISSUE TITLE
Unsupported Device Request

### ISSUE THREAD

**Issue by LivMLeo** [elad-bar/ha-tuya-dynamic#7]
Hey, the latest fix got it up and running thanks! after making the changes I think we have an unsupported device with our airfryer - as the entities are still not showing up (it feels so close !)  - would it be possible to get it added when you have a chance please!  
The diagnostics download wont work on the CE integration but from the original TUYA integration with DP it is (abbreviated the below) : 
.....
 
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "44",
    "app_type": "smartlife",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "T22",
    "model": "T22",
    "category": "kqzg",
    "product_id": "egd3t0rpwfqgcttg",
    "product_name": "T22",
    "online": false,
    "sub": false,
    "time_zone": "+00:00",
    "active_time": "2023-01-21T18:10:32+00:00",
    "create_time": "2023-01-21T17:55:44+00:00",
    "update_time": "2023-01-21T18:10:35+00:00",
    "function": {
      "switch": {
        "type": "Boolean",
        "value": {}
      },
      "start": {
        "type": "Boolean",
        "value": {}
      },
      "mode": {
        "type": "Enum",
        "value": {
          "range": [
            "fries",
            "wings",
            "steak",
            "shrimp",
            "fish",
            "onionrings",
            "pizza",
            "bacon",
            "cake",
            "toast",
            "vegetable",
            "diy",
            "cloud",
            "default",
            "warm",
            "preheat"
          ]
        }
      },
      "cloud_recipe_number": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999999,
          "scale": 0,
          "step": 1
        }
      },
      "cook_temperature": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 75,
          "max": 400,
          "scale": 0,
          "step": 5
        }
      },
      "appointment_time": {
        "type": "Integer",
        "value": {
          "unit": "min",
          "min": 0,
          "max": 240,
          "scale": 0,
          "step": 1
        }
      },
      "cook_time": {
        "type": "Integer",
        "value": {
          "unit": "min",
          "min": 1,
          "max": 720,
          "scale": 0,
          "step": 1
        }
      },
      "multistep": {
        "type": "Raw",
        "value": {}
      },
      "pause": {
        "type": "Boolean",
        "value": {}
      },
      "temp_unit_convert": {
        "type": "Enum",
        "value": {
          "range": [
            "c",
            "f"
          ]
        }
      },
      "preheat": {
        "type": "Boolean",
        "value": {}
      },
      "cooking_report": {
        "type": "Raw",
        "value": {}
      },
      "warm": {
        "type": "Boolean",
        "value": {}
      },
      "mode_voice": {
        "type": "Enum",
        "value": {
          "range": [
            "fries",
            "wings",
            "steak",
            "shrimp",
            "fish",
            "onionrings",
            "pizza",
            "bacon",
            "cake",
            "toast",
            "vegetable",
            "diy",
            "cloud",
            "default",
            "warm",
            "preheat"
          ]
        }
      }
    },
    "status_range": {
      "switch": {
        "type": "Boolean",
        "value": {}
      },
      "start": {
        "type": "Boolean",
        "value": {}
      },
      "mode": {
        "type": "Enum",
        "value": {
          "range": [
            "fries",
            "wings",
            "steak",
            "shrimp",
            "fish",
            "onionrings",
            "pizza",
            "bacon",
            "cake",
            "toast",
            "vegetable",
            "diy",
            "cloud",
            "default",
            "warm",
            "preheat"
          ]
        }
      },
      "cloud_recipe_number": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999999,
          "scale": 0,
          "step": 1
        }
      },
      "status": {
        "type": "Enum",
        "value": {
          "range": [
            "standby",
            "appointment",
            "cooking",
            "done",
            "warm",
            "off",
            "stop"
          ]
        }
      },
      "cook_temperature": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 75,
          "max": 400,
          "scale": 0,
          "step": 5
        }
      },
      "temp_current": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 1,
          "max": 500,
          "scale": 0,
          "step": 1
        }
      },
      "appointment_time": {
        "type": "Integer",
        "value": {
          "unit": "min",
          "min": 0,
          "max": 240,
          "scale": 0,
          "step": 1
        }
      },
      "cook_time": {
        "type": "Integer",
        "value": {
          "unit": "min",
          "min": 1,
          "max": 720,
          "scale": 0,
          "step": 1
        }
      },
      "remain_time": {
        "type": "Integer",
        "value": {
          "unit": "min",
          "min": 0,
          "max": 720,
          "scale": 0,
          "step": 1
        }
      },
      "multistep": {
        "type": "Raw",
        "value": {}
      },
      "fault": {
        "type": "Bitmap",
        "value": {
          "label": [
            "motor_fault"
          ],
          "maxlen": 1
        }
      },
      "pause": {
        "type": "Boolean",
        "value": {}
      },
      "temp_unit_convert": {
        "type": "Enum",
        "value": {
          "range": [
            "c",
            "f"
          ]
        }
      },
      "preheat": {
        "type": "Boolean",
        "value": {}
      },
      "cooking_report": {
        "type": "Raw",
        "value": {}
      },
      "warm": {
        "type": "Boolean",
        "value": {}
      },
      "cookrecord": {
        "type": "String",
        "value": {
          "maxlen": 255
        }
      },
      "gzt": {
        "type": "Boolean",
        "value": {}
      },
      "shake": {
        "type": "Enum",
        "value": {
          "range": [
            "0",
            "1"
          ]
        }
      },
      "stage_time": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": 0,
          "max": 720,
          "scale": 0,
          "step": 1
        }
      },
      "mode_voice": {
        "type": "Enum",
        "value": {
          "range": [
            "fries",
            "wings",
            "steak",
            "shrimp",
            "fish",
            "onionrings",
            "pizza",
            "bacon",
            "cake",
            "toast",
            "vegetable",
            "diy",
            "cloud",
            "default",
            "warm",
            "preheat"
          ]
        }
      }
    },
    "status": {
      "switch": false,
      "start": true,
      "mode": "default",
      "cloud_recipe_number": 0,
      "status": "off",
      "cook_temperature": 175,
      "temp_current": 174,
      "appointment_time": 0,
      "cook_time": 8,
      "remain_time": 15,
      "multistep": "",
      "fault": 0,
      "pause": true,
      "temp_unit_convert": "c",
      "preheat": false,
      "cooking_report": "",
      "warm": false,
      "cookrecord": "000000001750080700",
      "gzt": false,
      "shake": 0,
      "stage_time": 1,
      "mode_voice": "fries"
    },
    "home_assistant": {
      "name": "T22",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }
  }
}

**Comment by elad-bar** [comment]
@LivMLeo thanks for the details, i will try to add the entities later this week

**Comment by elad-bar** [comment]
You have mentioned that you didn't manage to extract the diagnostic data from TuyaCE component, did you have an error in logs? 
In case you did, can you report it as an issue and share the error message? 

Thanks

**Comment by elad-bar** [comment]
I checked the diganostic and it works for me, if you can use it and send also the gaps / unsupported section it would be great as it holds the configuration to set up easily

**Comment by LivMLeo** [comment]
Hi, just tried it again but on the download diagnostics using the CE integration It starts a download but then i get 'Failed - Server problem' or 'Failed - Needs Authorisation' but seems to work on the other integration diagnostic downloads - is there something i need to set up to be able to access this? sorry - thanks again!

**Comment by elad-bar** [comment]
can you please post the logs for it?

thanks

**Comment by elad-bar** [comment]
according to the JSON there are 4 modes and 3 fan modes, can you please specify them?
for now, added them as numbers, once you will provide the values I can convert them to drop down,
to make it work like climate component I need to investigate the implementation of the climate component and adjust it to support IR remote

**Comment by elad-bar** [comment]
added the support you can try to run the service `tuya_ce.update_remote_configuration`, 
it will fetch the up to date configuration, the just reload the integration and you should see the entities,
please check it if it works for you and let me know

thanks

**Comment by elad-bar** [comment]
Project is no longer supported, switched to LocalTuya + Zigbee2MQTT
