### ISSUE TITLE
New device - air conditioning unsupported

### ISSUE THREAD

**Issue by Bobsilvio** [elad-bar/ha-tuya-dynamic#8]
hi, thanks for fix tuya ce.

`  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "39",
    "app_type": "smartlife",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "Air Conditioning",
    "model": null,
    "category": "infrared_ac",
    "product_id": "jllh2kdbGM0QTdf1",
    "product_name": "Air Conditioning",
    "online": true,
    "sub": true,
    "time_zone": "+08:00",
    "active_time": "2021-07-10T08:45:06+00:00",
    "create_time": "2021-07-10T08:45:06+00:00",
    "update_time": "2021-12-11T14:22:55+00:00",
    "function": {
      "F": {
        "type": "ENUM",
        "value": {
          "min": 0,
          "max": 3,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      },
      "M": {
        "type": "ENUM",
        "value": {
          "min": 0,
          "max": 4,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      },
      "PowerOff": {
        "type": "STRING",
        "value": "PowerOff"
      },
      "PowerOn": {
        "type": "STRING",
        "value": "PowerOn"
      },
      "T": {
        "type": "ENUM",
        "value": {
          "min": 16,
          "max": 30,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      }
    },
    "status_range": {
      "wind": {
        "type": "ENUM",
        "value": {
          "min": 0,
          "max": 3,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      },
      "mode": {
        "type": "ENUM",
        "value": {
          "min": 0,
          "max": 4,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      },
      "power": {
        "type": "BOOLEAN",
        "value": {}
      },
      "temp": {
        "type": "ENUM",
        "value": {
          "min": 16,
          "max": 30,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      }
    },
    "status": {},
    "home_assistant": {
      "name": "Air Conditioning",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }`

**Comment by elad-bar** [comment]
Thanks for the details, will get to it later this week,
Did you use the Tuya CE component to extract the diagnostic tool?
In case you did, do you have gaps and unsupported_devices sections?

Thanks

**Comment by elad-bar** [comment]
can you please send me the gaps / unsupported device section?
it holds the additional configuration to set up

**Comment by Bobsilvio** [comment]
How find?

**Comment by Bobsilvio** [comment]
Air Conditioning (unsupported)
da Tuya 

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.8.7",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "4.4.180+",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.27.1",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "tuya_ce": {
      "version": "0.0.1",
      "requirements": [
        "tuya-iot-py-sdk==0.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya",
    "name": "Tuya",
    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "dependencies": [
      "ffmpeg"
    ],
    "codeowners": [
      "@Tuya",
      "@zlinoliver",
      "@frenck"
    ],
    "config_flow": true,
    "iot_class": "cloud_push",
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "loggers": [
      "tuya_iot"
    ],
    "is_built_in": true
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "39",
    "app_type": "smartlife",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "Air Conditioning",
    "model": null,
    "category": "infrared_ac",
    "product_id": "jllh2kdbGM0QTdf1",
    "product_name": "Air Conditioning",
    "online": true,
    "sub": true,
    "time_zone": "+08:00",
    "active_time": "2021-07-10T08:45:06+00:00",
    "create_time": "2021-07-10T08:45:06+00:00",
    "update_time": "2021-12-11T14:22:55+00:00",
    "function": {
      "F": {
        "type": "ENUM",
        "value": {
          "min": 0,
          "max": 3,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      },
      "M": {
        "type": "ENUM",
        "value": {
          "min": 0,
          "max": 4,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      },
      "PowerOff": {
        "type": "STRING",
        "value": "PowerOff"
      },
      "PowerOn": {
        "type": "STRING",
        "value": "PowerOn"
      },
      "T": {
        "type": "ENUM",
        "value": {
          "min": 16,
          "max": 30,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      }
    },
    "status_range": {
      "wind": {
        "type": "ENUM",
        "value": {
          "min": 0,
          "max": 3,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      },
      "mode": {
        "type": "ENUM",
        "value": {
          "min": 0,
          "max": 4,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      },
      "power": {
        "type": "BOOLEAN",
        "value": {}
      },
      "temp": {
        "type": "ENUM",
        "value": {
          "min": 16,
          "max": 30,
          "scale": 0,
          "step": 1,
          "type": "Integer"
        }
      }
    },
    "status": {},
    "home_assistant": {
      "name": "Air Conditioning",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }
  }
}

**Comment by Bobsilvio** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.8.7",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "4.4.180+",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.27.1",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "tuya_ce": {
      "version": "0.0.1",
      "requirements": [
        "tuya-iot-py-sdk==0.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya",
    "name": "Tuya",
    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "dependencies": [
      "ffmpeg"
    ],
    "codeowners": [
      "@Tuya",
      "@zlinoliver",
      "@frenck"
    ],
    "config_flow": true,
    "iot_class": "cloud_push",
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "loggers": [
      "tuya_iot"
    ],
    "is_built_in": true
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "39",
    "app_type": "smartlife",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "Smart IR",
    "model": null,
    "category": "qt",
    "product_id": "JvihcnJiXk1grl60",
    "product_name": "Smart IR",
    "online": true,
    "sub": false,
    "time_zone": "+01:00",
    "active_time": "2021-06-24T17:13:59+00:00",
    "create_time": "2021-06-24T17:13:59+00:00",
    "update_time": "2022-06-26T12:42:21+00:00",
    "function": {},
    "status_range": {},
    "status": {},
    "home_assistant": {
      "name": "Smart IR",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }
  }
}

**Comment by Bobsilvio** [comment]
https://ibb.co/c6fGZfD

**Comment by elad-bar** [comment]
According to the following section, you are using the regular Tuya integration to extract the diagnostic infromation,
```
"integration_manifest": {
"domain": "tuya",
"name": "Tuya",
```

can you please install the Tuya CE component and add additional intergration of it (it can work side by side with the original one), and only then extract the diagnnostic information,
by having it, I will be able to take the result of it and just add it to the configuration while will make it available in your system without re-installing the Tuya CE.

otherwise, I need to parse it in my environment which can take more time (since I need to work on it instead of just adding the output from the json you will send)

thanks

**Comment by Bobsilvio** [comment]
i have installed tuya ce
https://ibb.co/tpCgsHb

and this in config

logger:
  default: warning
  logs:
    custom_components.tuya_ce: debug

**Comment by elad-bar** [comment]
That's great, but the file you have shared was generated by Tuya not Tuya CE

**Comment by Bobsilvio** [comment]
please tell how generate file by tuya ce

**Comment by elad-bar** [comment]
To be clearer,  after installing it, you need to add a new integration of it (Tuya CE), once it was loaded you can extract the diagnostic data

**Comment by Bobsilvio** [comment]
https://ibb.co/NNshkzr

**Comment by Bobsilvio** [comment]
missing "install"
https://ibb.co/s6hVdM1

**Comment by elad-bar** [comment]
To install the custom component from HACS you need to click on the download button on the right bottom corner of the UI, it's part of HACS functionality.
```
Installations via HACS
Add as custom repository
look for "Tuya CE" and install and restart
```

Once you have installed the custom component and restarted the HA
```
In Settings --> Devices & Services - (Lower Right) "Add Integration"
```

choose Tuya CE to add integration

**Comment by Bobsilvio** [comment]
I'm sorry, I feel stupid. but i think something is wrong. The integration does not appear.
look photo
https://ibb.co/NNshkzr
only original tuya

**Comment by elad-bar** [comment]
that's ok... :)
is it after restart? 
do you have errors in log related to the component (Tuya CE)?
in case you have restarted and no errors in log, maybe try to clean cache / open in incognito,
if there are some errors in log, please post them

thanks

**Comment by Bobsilvio** [comment]
ok, problem is old HA and old HACS..

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.1.7",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "4.4.180+",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.30.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tuya_ce": {
      "version": "0.0.2",
      "requirements": [
        "tuya-iot-py-sdk==0.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_ce",
    "name": "Tuya CE",
    "documentation": "https://github.com/elad-bar/ha-tuya-ce",
    "issue_tracker": "https://github.com/elad-bar/ha-tuya-ce/issues",
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "dependencies": [
      "ffmpeg",
      "tuya"
    ],
    "codeowners": [
      "@elad-bar"
    ],
    "config_flow": true,
    "iot_class": "cloud_push",
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "integration_type": "hub",
    "loggers": [
      "tuya_iot"
    ],
    "version": "0.0.2",
    "is_built_in": false
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "39",
    "app_type": "smartlife",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "devices": [
      {
        "name": "Smart IR",
        "model": null,
        "category": "qt",
        "product_id": "JvihcnJiXk1grl60",
        "product_name": "Smart IR",
        "online": true,
        "sub": false,
        "time_zone": "+01:00",
        "active_time": "2021-06-24T17:13:59+00:00",
        "create_time": "2021-06-24T17:13:59+00:00",
        "update_time": "2022-06-26T12:42:21+00:00",
        "function": {},
        "status_range": {},
        "status": {},
        "home_assistant": {
          "name": "Smart IR",
          "name_by_user": null,
          "disabled": false,
          "disabled_by": null,
          "entities": []
        }
      },
      {
        "name": "Ghirlanda",
        "model": "SP22-10A-FTY",
        "category": "cz",
        "product_id": "vnya2spfopsh9lro",
        "product_name": "Smart socket",
        "online": false,
        "sub": false,
        "time_zone": "+01:00",
        "active_time": "2021-11-27T17:24:51+00:00",
        "create_time": "2021-11-27T17:24:51+00:00",
        "update_time": "2021-12-20T12:24:18+00:00",
        "function": {
          "switch_1": {
            "type": "Boolean",
            "value": {}
          },
          "countdown_1": {
            "type": "Integer",
            "value": {
              "unit": "s",
              "min": 0,
              "max": 86400,
              "scale": 0,
              "step": 1
            }
          }
        },
        "status_range": {
          "switch_1": {
            "type": "Boolean",
            "value": {}
          },
          "countdown_1": {
            "type": "Integer",
            "value": {
              "unit": "s",
              "min": 0,
              "max": 86400,
              "scale": 0,
              "step": 1
            }
          },
          "add_ele": {
            "type": "Integer",
            "value": {
              "unit": "",
              "min": 0,
              "max": 50000,
              "scale": 3,
              "step": 100
            }
          },
          "cur_current": {
            "type": "Integer",
            "value": {
              "unit": "mA",
              "min": 0,
              "max": 30000,
              "scale": 0,
              "step": 1
            }
          },
          "cur_power": {
            "type": "Integer",
            "value": {
              "unit": "W",
              "min": 0,
              "max": 50000,
              "scale": 1,
              "step": 1
            }
          },
          "cur_voltage": {
            "type": "Integer",
            "value": {
              "unit": "V",
              "min": 0,
              "max": 5000,
              "scale": 1,
              "step": 1
            }
          }
        },
        "status": {
          "switch_1": true,
          "countdown_1": 0,
          "add_ele": 3,
          "cur_current": 38,
          "cur_power": 53,
          "cur_voltage": 2308
        },
        "home_assistant": {
          "name": "Ghirlanda",
          "name_by_user": null,
          "disabled": false,
          "disabled_by": null,
          "entities": [
            {
              "disabled": true,
              "disabled_by": "integration",
              "entity_category": null,
              "device_class": null,
              "original_device_class": "current",
              "icon": null,
              "original_icon": null,
              "unit_of_measurement": "A",
              "state": null
            },
            {
              "disabled": true,
              "disabled_by": "integration",
              "entity_category": null,
              "device_class": null,
              "original_device_class": "power",
              "icon": null,
              "original_icon": null,
              "unit_of_measurement": "W",
              "state": null
            },
            {
              "disabled": true,
              "disabled_by": "integration",
              "entity_category": null,
              "device_class": null,
              "original_device_class": "voltage",
              "icon": null,
              "original_icon": null,
              "unit_of_measurement": "V",
              "state": null
            },
            {
              "disabled": false,
              "disabled_by": null,
              "entity_category": null,
              "device_class": null,
              "original_device_class": "outlet",
              "icon": null,
              "original_icon": null,
              "unit_of_measurement": null,
              "state": {
                "entity_id": "switch.ghirlanda_socket_1_2",
                "state": "unavailable",
                "attributes": {
                  "device_class": "outlet",
                  "friendly_name": "Ghirlanda Socket 1"
                },
                "last_changed": "2023-01-25T14:17:39.369761+00:00",
                "last_updated": "2023-01-25T14:17:39.369761+00:00"
              }
            }
          ]
        }
      },
      {
        "name": "Air Conditioning",
        "model": null,
        "category": "infrared_ac",
        "product_id": "jllh2kdbGM0QTdf1",
        "product_name": "Air Conditioning",
        "online": true,
        "sub": true,
        "time_zone": "+08:00",
        "active_time": "2021-07-10T08:45:06+00:00",
        "create_time": "2021-07-10T08:45:06+00:00",
        "update_time": "2021-12-11T14:22:55+00:00",
        "function": {
          "F": {
            "type": "ENUM",
            "value": {
              "min": 0,
              "max": 3,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          },
          "M": {
            "type": "ENUM",
            "value": {
              "min": 0,
              "max": 4,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          },
          "PowerOff": {
            "type": "STRING",
            "value": "PowerOff"
          },
          "PowerOn": {
            "type": "STRING",
            "value": "PowerOn"
          },
          "T": {
            "type": "ENUM",
            "value": {
              "min": 16,
              "max": 30,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          }
        },
        "status_range": {
          "wind": {
            "type": "ENUM",
            "value": {
              "min": 0,
              "max": 3,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          },
          "mode": {
            "type": "ENUM",
            "value": {
              "min": 0,
              "max": 4,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          },
          "power": {
            "type": "BOOLEAN",
            "value": {}
          },
          "temp": {
            "type": "ENUM",
            "value": {
              "min": 16,
              "max": 30,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          }
        },
        "status": {},
        "home_assistant": {
          "name": "Air Conditioning",
          "name_by_user": null,
          "disabled": false,
          "disabled_by": null,
          "entities": []
        }
      }
    ],
    "gaps": {
      "cz": {
        "number": {
          "countdown_1": {
            "type": "Integer",
            "value": {
              "unit": "s",
              "min": 0,
              "max": 86400,
              "scale": 0,
              "step": 1
            },
            "matches": {}
          }
        }
      },
      "infrared_ac": {
        "sensor": {
          "wind": {
            "type": "Enum",
            "value": {
              "min": 0,
              "max": 3,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            },
            "matches": {}
          },
          "mode": {
            "type": "Enum",
            "value": {
              "min": 0,
              "max": 4,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            },
            "matches": {
              "select": [
                {
                  "key": "mode",
                  "entity_category": "config",
                  "icon": "mdi:layers-outline",
                  "name": "Mode",
                  "translation_key": "vacuum_mode"
                },
                {
                  "key": "mode",
                  "entity_category": "config",
                  "name": "Mode",
                  "translation_key": "curtain_mode"
                },
                {
                  "key": "mode",
                  "icon": "mdi:coffee",
                  "name": "Mode"
                },
                {
                  "key": "mode",
                  "entity_category": "config",
                  "name": "Mode",
                  "translation_key": "fingerbot_mode"
                }
              ]
            }
          },
          "temp": {
            "type": "Enum",
            "value": {
              "min": 16,
              "max": 30,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            },
            "matches": {
              "number": [
                {
                  "key": "temp",
                  "device_class": "temperature",
                  "icon": "mdi:thermometer-lines",
                  "name": "Temperature"
                }
              ],
              "sensor": [
                {
                  "key": "temp",
                  "device_class": "temperature",
                  "entity_registry_enabled_default": true,
                  "name": "Temperature",
                  "state_class": "measurement"
                }
              ]
            }
          }
        },
        "select": {
          "PowerOff": {
            "type": "String",
            "matches": {}
          },
          "PowerOn": {
            "type": "String",
            "matches": {}
          }
        }
      }
    },
    "unsupported_devices": {
      "qt": [
        {
          "name": "Smart IR",
          "model": null,
          "product_name": "Smart IR"
        }
      ]
    }
  }
}

**Comment by elad-bar** [comment]
added the support you can try to run the service `tuya_ce.update_remote_configuration`, 
it will fetch the up to date configuration, the just reload the integration and you should see the entities,
please check it if it works for you and let me know.

It will just create the entities, to get the select and sensor cleaner values, you will need to install v0.0.3,
in the future i will add it as well to the automated process (including reloading and grabing the tranlsation of entities).

thanks

**Comment by Bobsilvio** [comment]
No work

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.1.7",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "4.4.180+",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.30.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tuya_ce": {
      "version": "0.0.3",
      "requirements": [
        "tuya-iot-py-sdk==0.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_ce",
    "name": "Tuya CE",
    "documentation": "https://github.com/elad-bar/ha-tuya-ce",
    "issue_tracker": "https://github.com/elad-bar/ha-tuya-ce/issues",
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "dependencies": [
      "ffmpeg",
      "tuya"
    ],
    "codeowners": [
      "@elad-bar"
    ],
    "config_flow": true,
    "iot_class": "cloud_push",
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "integration_type": "hub",
    "loggers": [
      "tuya_iot"
    ],
    "version": "0.0.3",
    "is_built_in": false
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "39",
    "app_type": "smartlife",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "devices": [
      {
        "name": "Smart IR",
        "model": null,
        "category": "qt",
        "product_id": "JvihcnJiXk1grl60",
        "product_name": "Smart IR",
        "online": true,
        "sub": false,
        "time_zone": "+01:00",
        "active_time": "2021-06-24T17:13:59+00:00",
        "create_time": "2021-06-24T17:13:59+00:00",
        "update_time": "2022-06-26T12:42:21+00:00",
        "function": {},
        "status_range": {},
        "status": {},
        "home_assistant": {
          "name": "Smart IR",
          "name_by_user": null,
          "disabled": false,
          "disabled_by": null,
          "entities": []
        }
      },
      {
        "name": "Ghirlanda",
        "model": "SP22-10A-FTY",
        "category": "cz",
        "product_id": "vnya2spfopsh9lro",
        "product_name": "Smart socket",
        "online": false,
        "sub": false,
        "time_zone": "+01:00",
        "active_time": "2021-11-27T17:24:51+00:00",
        "create_time": "2021-11-27T17:24:51+00:00",
        "update_time": "2021-12-20T12:24:18+00:00",
        "function": {
          "switch_1": {
            "type": "Boolean",
            "value": {}
          },
          "countdown_1": {
            "type": "Integer",
            "value": {
              "unit": "s",
              "min": 0,
              "max": 86400,
              "scale": 0,
              "step": 1
            }
          }
        },
        "status_range": {
          "switch_1": {
            "type": "Boolean",
            "value": {}
          },
          "countdown_1": {
            "type": "Integer",
            "value": {
              "unit": "s",
              "min": 0,
              "max": 86400,
              "scale": 0,
              "step": 1
            }
          },
          "add_ele": {
            "type": "Integer",
            "value": {
              "unit": "",
              "min": 0,
              "max": 50000,
              "scale": 3,
              "step": 100
            }
          },
          "cur_current": {
            "type": "Integer",
            "value": {
              "unit": "mA",
              "min": 0,
              "max": 30000,
              "scale": 0,
              "step": 1
            }
          },
          "cur_power": {
            "type": "Integer",
            "value": {
              "unit": "W",
              "min": 0,
              "max": 50000,
              "scale": 1,
              "step": 1
            }
          },
          "cur_voltage": {
            "type": "Integer",
            "value": {
              "unit": "V",
              "min": 0,
              "max": 5000,
              "scale": 1,
              "step": 1
            }
          }
        },
        "status": {
          "switch_1": true,
          "countdown_1": 0,
          "add_ele": 3,
          "cur_current": 38,
          "cur_power": 53,
          "cur_voltage": 2308
        },
        "home_assistant": {
          "name": "Ghirlanda",
          "name_by_user": null,
          "disabled": false,
          "disabled_by": null,
          "entities": [
            {
              "disabled": true,
              "disabled_by": "integration",
              "entity_category": null,
              "device_class": null,
              "original_device_class": "current",
              "icon": null,
              "original_icon": null,
              "unit_of_measurement": "A",
              "state": null
            },
            {
              "disabled": true,
              "disabled_by": "integration",
              "entity_category": null,
              "device_class": null,
              "original_device_class": "power",
              "icon": null,
              "original_icon": null,
              "unit_of_measurement": "W",
              "state": null
            },
            {
              "disabled": true,
              "disabled_by": "integration",
              "entity_category": null,
              "device_class": null,
              "original_device_class": "voltage",
              "icon": null,
              "original_icon": null,
              "unit_of_measurement": "V",
              "state": null
            },
            {
              "disabled": false,
              "disabled_by": null,
              "entity_category": null,
              "device_class": null,
              "original_device_class": "outlet",
              "icon": null,
              "original_icon": null,
              "unit_of_measurement": null,
              "state": {
                "entity_id": "switch.ghirlanda_socket_1_2",
                "state": "unavailable",
                "attributes": {
                  "device_class": "outlet",
                  "friendly_name": "Ghirlanda Socket 1"
                },
                "last_changed": "2023-01-25T15:53:42.475830+00:00",
                "last_updated": "2023-01-25T16:19:30.670095+00:00"
              }
            }
          ]
        }
      },
      {
        "name": "Air Conditioning",
        "model": null,
        "category": "infrared_ac",
        "product_id": "jllh2kdbGM0QTdf1",
        "product_name": "Air Conditioning",
        "online": true,
        "sub": true,
        "time_zone": "+08:00",
        "active_time": "2021-07-10T08:45:06+00:00",
        "create_time": "2021-07-10T08:45:06+00:00",
        "update_time": "2021-12-11T14:22:55+00:00",
        "function": {
          "F": {
            "type": "ENUM",
            "value": {
              "min": 0,
              "max": 3,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          },
          "M": {
            "type": "ENUM",
            "value": {
              "min": 0,
              "max": 4,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          },
          "PowerOff": {
            "type": "STRING",
            "value": "PowerOff"
          },
          "PowerOn": {
            "type": "STRING",
            "value": "PowerOn"
          },
          "T": {
            "type": "ENUM",
            "value": {
              "min": 16,
              "max": 30,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          }
        },
        "status_range": {
          "wind": {
            "type": "ENUM",
            "value": {
              "min": 0,
              "max": 3,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          },
          "mode": {
            "type": "ENUM",
            "value": {
              "min": 0,
              "max": 4,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          },
          "power": {
            "type": "BOOLEAN",
            "value": {}
          },
          "temp": {
            "type": "ENUM",
            "value": {
              "min": 16,
              "max": 30,
              "scale": 0,
              "step": 1,
              "type": "Integer"
            }
          }
        },
        "status": {},
        "home_assistant": {
          "name": "Air Conditioning",
          "name_by_user": null,
          "disabled": false,
          "disabled_by": null,
          "entities": []
        }
      }
    ],
    "gaps": {
      "cz": {
        "number": {
          "countdown_1": {
            "type": "Integer",
            "value": {
              "unit": "s",
              "min": 0,
              "max": 86400,
              "scale": 0,
              "step": 1
            },
            "matches": {}
          }
        }
      },
      "infrared_ac": {
        "select": {
          "PowerOff": {
            "type": "String",
            "matches": {
              "switch": [
                {
                  "key": "PowerOff",
                  "name": "Power Off"
                }
              ]
            }
          },
          "PowerOn": {
            "type": "String",
            "matches": {
              "switch": [
                {
                  "key": "PowerOn",
                  "name": "Power On"
                }
              ]
            }
          }
        }
      }
    },
    "unsupported_devices": {
      "qt": [
        {
          "name": "Smart IR",
          "model": null,
          "product_name": "Smart IR"
        }
      ]
    }
  }
}

**Comment by elad-bar** [comment]
I have a IR remote of Tuya which I'm not using, will try during the weekend to find a solution for that,
the IR remote is bit different than many other devices as its status different than commands

**Comment by Bobsilvio** [comment]
news?

**Comment by elad-bar** [comment]
left Tuya and switched to Zigbee2MQTT with most of the products, for the 4 wifi products, switched to Tuya Local.
hopefully soon I will get a unit of IR blaster so I will be able to debug to see how I can assist with that.

although I'm not using Tuya, will try to maintain that integration, maybe one day I will get back to it :)

**Comment by elad-bar** [comment]
Project is no longer supported, switched to LocalTuya + Zigbee2MQTT
